-- SI-LEMLATVOK — Seed data
-- Auto-generated from src/data/staticData.ts, isinya identik dengan mock data lama.
-- Jalankan SETELAH schema.sql, di Supabase Dashboard > SQL Editor.

-- ============================================================
-- dashboard_periods
-- ============================================================
insert into dashboard_periods (period, label, as_of_date, lpk, lpk_delta, akreditasi, akreditasi_delta, aktif, aktif_delta, sertifikat, sertifikat_delta, asesor, asesor_note, sla, sla_over, workload, jenis, status, biaya, trend, trend_months, top_provinces, process) values
  ('mei2026', 'Mei 2026', '19 Mei 2026 10:30 WIB', 16382, 3.2, 1504, 4.5, 1287, 8.7, 732, 12.1, 346, 58, 92, 102, '8,5', '[{"label": "Akreditasi Baru", "value": 687, "color": "#2f6fed"}, {"label": "Reakreditasi", "value": 412, "color": "#12a454"}, {"label": "Penambahan Program", "value": 188, "color": "#e88a1b"}]'::jsonb, '[{"label": "Verifikasi", "value": 312, "color": "#2f6fed"}, {"label": "Asesmen", "value": 541, "color": "#12a454"}, {"label": "Review", "value": 213, "color": "#e88a1b"}, {"label": "Menunggu Keputusan", "value": 221, "color": "#7c4dee"}]'::jsonb, '[{"label": "APBN", "value": 784, "color": "#2f6fed"}, {"label": "APBD", "value": 219, "color": "#12a454"}, {"label": "Mandiri", "value": 284, "color": "#e88a1b"}]'::jsonb, '[320, 410, 560, 780, 700, 980, 940, 950, 880, 1010, 1150, 1287]'::jsonb, '["Jun", "Jul", "Agt", "Sep", "Okt", "Nov", "Des", "Jan", "Feb", "Mar", "Apr", "Mei"]'::jsonb, '[{"province": "Jawa Barat", "count": 214}, {"province": "Jawa Timur", "count": 187}, {"province": "Jawa Tengah", "count": 152}, {"province": "Sumatera Utara", "count": 98}, {"province": "Sulawesi Selatan", "count": 76}]'::jsonb, '[{"label": "Pengajuan", "value": 1287, "pct": 100}, {"label": "Verifikasi", "value": 975, "pct": 75.7}, {"label": "Penugasan", "value": 821, "pct": 63.8}, {"label": "Asesmen", "value": 541, "pct": 42}, {"label": "Review", "value": 213, "pct": 16.5}, {"label": "Keputusan", "value": 187, "pct": 14.5}, {"label": "Sertifikat", "value": 732, "pct": null}]'::jsonb),
  ('apr2026', 'April 2026', '30 April 2026 17:00 WIB', 15870, 2.6, 1439, 3.9, 1184, 5.1, 653, 9.8, 339, 55, 90, 118, '8,1', '[{"label": "Akreditasi Baru", "value": 612, "color": "#2f6fed"}, {"label": "Reakreditasi", "value": 389, "color": "#12a454"}, {"label": "Penambahan Program", "value": 183, "color": "#e88a1b"}]'::jsonb, '[{"label": "Verifikasi", "value": 287, "color": "#2f6fed"}, {"label": "Asesmen", "value": 498, "color": "#12a454"}, {"label": "Review", "value": 196, "color": "#e88a1b"}, {"label": "Menunggu Keputusan", "value": 203, "color": "#7c4dee"}]'::jsonb, '[{"label": "APBN", "value": 711, "color": "#2f6fed"}, {"label": "APBD", "value": 201, "color": "#12a454"}, {"label": "Mandiri", "value": 272, "color": "#e88a1b"}]'::jsonb, '[290, 375, 510, 720, 655, 905, 880, 900, 860, 955, 1050, 1184]'::jsonb, '["Jun", "Jul", "Agt", "Sep", "Okt", "Nov", "Des", "Jan", "Feb", "Mar", "Apr", "Mei"]'::jsonb, '[{"province": "Jawa Barat", "count": 198}, {"province": "Jawa Timur", "count": 171}, {"province": "Jawa Tengah", "count": 140}, {"province": "Sumatera Utara", "count": 90}, {"province": "Sulawesi Selatan", "count": 69}]'::jsonb, '[{"label": "Pengajuan", "value": 1184, "pct": 100}, {"label": "Verifikasi", "value": 882, "pct": 74.5}, {"label": "Penugasan", "value": 751, "pct": 63.4}, {"label": "Asesmen", "value": 498, "pct": 42.1}, {"label": "Review", "value": 196, "pct": 16.6}, {"label": "Keputusan", "value": 173, "pct": 14.6}, {"label": "Sertifikat", "value": 653, "pct": null}]'::jsonb),
  ('mar2026', 'Maret 2026', '31 Maret 2026 16:00 WIB', 15420, 1.9, 1378, 3.1, 1102, 4, 588, 7.4, 331, 52, 88, 132, '7,6', '[{"label": "Akreditasi Baru", "value": 565, "color": "#2f6fed"}, {"label": "Reakreditasi", "value": 362, "color": "#12a454"}, {"label": "Penambahan Program", "value": 175, "color": "#e88a1b"}]'::jsonb, '[{"label": "Verifikasi", "value": 264, "color": "#2f6fed"}, {"label": "Asesmen", "value": 462, "color": "#12a454"}, {"label": "Review", "value": 178, "color": "#e88a1b"}, {"label": "Menunggu Keputusan", "value": 198, "color": "#7c4dee"}]'::jsonb, '[{"label": "APBN", "value": 662, "color": "#2f6fed"}, {"label": "APBD", "value": 188, "color": "#12a454"}, {"label": "Mandiri", "value": 252, "color": "#e88a1b"}]'::jsonb, '[260, 340, 470, 660, 600, 845, 810, 835, 795, 880, 965, 1102]'::jsonb, '["Jun", "Jul", "Agt", "Sep", "Okt", "Nov", "Des", "Jan", "Feb", "Mar", "Apr", "Mei"]'::jsonb, '[{"province": "Jawa Barat", "count": 180}, {"province": "Jawa Timur", "count": 158}, {"province": "Jawa Tengah", "count": 129}, {"province": "Sumatera Utara", "count": 83}, {"province": "Sulawesi Selatan", "count": 63}]'::jsonb, '[{"label": "Pengajuan", "value": 1102, "pct": 100}, {"label": "Verifikasi", "value": 806, "pct": 73.1}, {"label": "Penugasan", "value": 679, "pct": 61.6}, {"label": "Asesmen", "value": 462, "pct": 41.9}, {"label": "Review", "value": 178, "pct": 16.2}, {"label": "Keputusan", "value": 160, "pct": 14.5}, {"label": "Sertifikat", "value": 588, "pct": null}]'::jsonb),
  ('q2026', 'Kuartal I 2026', '31 Maret 2026 · Kumulatif Kuartal I', 16382, 6.4, 1504, 9.7, 3573, 14.2, 1973, 21.6, 346, 58, 90, 352, '8,0', '[{"label": "Akreditasi Baru", "value": 1864, "color": "#2f6fed"}, {"label": "Reakreditasi", "value": 1163, "color": "#12a454"}, {"label": "Penambahan Program", "value": 546, "color": "#e88a1b"}]'::jsonb, '[{"label": "Verifikasi", "value": 863, "color": "#2f6fed"}, {"label": "Asesmen", "value": 1501, "color": "#12a454"}, {"label": "Review", "value": 587, "color": "#e88a1b"}, {"label": "Menunggu Keputusan", "value": 622, "color": "#7c4dee"}]'::jsonb, '[{"label": "APBN", "value": 2157, "color": "#2f6fed"}, {"label": "APBD", "value": 608, "color": "#12a454"}, {"label": "Mandiri", "value": 808, "color": "#e88a1b"}]'::jsonb, '[260, 340, 470, 660, 600, 845, 810, 835, 795, 880, 965, 3573]'::jsonb, '["Jun", "Jul", "Agt", "Sep", "Okt", "Nov", "Des", "Jan", "Feb", "Mar", "Apr", "Mei"]'::jsonb, '[{"province": "Jawa Barat", "count": 592}, {"province": "Jawa Timur", "count": 516}, {"province": "Jawa Tengah", "count": 421}, {"province": "Sumatera Utara", "count": 271}, {"province": "Sulawesi Selatan", "count": 208}]'::jsonb, '[{"label": "Pengajuan", "value": 3573, "pct": 100}, {"label": "Verifikasi", "value": 2663, "pct": 74.5}, {"label": "Penugasan", "value": 2251, "pct": 63}, {"label": "Asesmen", "value": 1501, "pct": 42}, {"label": "Review", "value": 587, "pct": 16.4}, {"label": "Keputusan", "value": 520, "pct": 14.6}, {"label": "Sertifikat", "value": 1973, "pct": null}]'::jsonb),
  ('y2026', 'Tahun 2026 (s.d. Mei)', '19 Mei 2026 · Kumulatif Tahun Berjalan', 16382, 9.8, 1504, 15.3, 5860, 22.5, 3218, 31.2, 346, 58, 91, 527, '8,3', '[{"label": "Akreditasi Baru", "value": 3055, "color": "#2f6fed"}, {"label": "Reakreditasi", "value": 1908, "color": "#12a454"}, {"label": "Penambahan Program", "value": 897, "color": "#e88a1b"}]'::jsonb, '[{"label": "Verifikasi", "value": 1415, "color": "#2f6fed"}, {"label": "Asesmen", "value": 2461, "color": "#12a454"}, {"label": "Review", "value": 963, "color": "#e88a1b"}, {"label": "Menunggu Keputusan", "value": 1021, "color": "#7c4dee"}]'::jsonb, '[{"label": "APBN", "value": 3540, "color": "#2f6fed"}, {"label": "APBD", "value": 997, "color": "#12a454"}, {"label": "Mandiri", "value": 1323, "color": "#e88a1b"}]'::jsonb, '[320, 410, 560, 780, 700, 980, 940, 950, 880, 1010, 1150, 5860]'::jsonb, '["Jun", "Jul", "Agt", "Sep", "Okt", "Nov", "Des", "Jan", "Feb", "Mar", "Apr", "Mei"]'::jsonb, '[{"province": "Jawa Barat", "count": 972}, {"province": "Jawa Timur", "count": 846}, {"province": "Jawa Tengah", "count": 690}, {"province": "Sumatera Utara", "count": 445}, {"province": "Sulawesi Selatan", "count": 342}]'::jsonb, '[{"label": "Pengajuan", "value": 5860, "pct": 100}, {"label": "Verifikasi", "value": 4370, "pct": 74.6}, {"label": "Penugasan", "value": 3692, "pct": 63}, {"label": "Asesmen", "value": 2461, "pct": 42}, {"label": "Review", "value": 963, "pct": 16.4}, {"label": "Keputusan", "value": 852, "pct": 14.5}, {"label": "Sertifikat", "value": 3218, "pct": null}]'::jsonb)
on conflict (period) do update set
  label = excluded.label, as_of_date = excluded.as_of_date;

-- ============================================================
-- notifications
-- ============================================================
insert into notifications (id, title, time, read) values
  ('n1', '5 pengajuan baru menunggu verifikasi', '10 menit lalu', false),
  ('n2', 'SLA pengajuan AKR-2026-0142 akan terlampaui besok', '1 jam lalu', false),
  ('n3', 'Sertifikat SERT-2026-0703 telah diterbitkan', '3 jam lalu', true),
  ('n4', 'Asesor Budi Santoso menyelesaikan asesmen lapangan', 'Kemarin', true)
on conflict (id) do nothing;

-- ============================================================
-- module_definitions
-- ============================================================
insert into module_definitions (key, nav_label, title, sub, add_label, cols, status_key, icon, show_badge, sort_order) values
  ('mod-pengajuan', 'Pengajuan Akreditasi', 'Pengajuan Akreditasi', 'Daftar seluruh pengajuan akreditasi yang masuk ke sistem.', 'Pengajuan Baru', '["ID Pengajuan", "Nama LPK", "Jenis Layanan", "Provinsi", "Tanggal Ajuan", "Status"]'::jsonb, 'Status', 'FileText', true, 0),
  ('mod-verifikasi', 'Verifikasi', 'Verifikasi Dokumen', 'Status verifikasi kelengkapan dokumen pengajuan.', 'Verifikasi Baru', '["ID Pengajuan", "Nama LPK", "Petugas Verifikasi", "Tanggal", "Status"]'::jsonb, 'Status', 'CheckSquare', true, 1),
  ('mod-penugasan', 'Penugasan Asesor', 'Penugasan Asesor', 'Alokasi asesor untuk setiap pengajuan yang lolos verifikasi.', 'Penugasan Asesor', '["ID Pengajuan", "Nama LPK", "Asesor Ditugaskan", "Tanggal Penugasan", "Status"]'::jsonb, 'Status', 'Users', true, 2),
  ('mod-asesmen', 'Asesmen', 'Asesmen Lapangan', 'Pelaksanaan dan hasil asesmen lapangan LPK.', 'Jadwal Asesmen', '["ID Pengajuan", "Nama LPK", "Asesor", "Tanggal Asesmen", "Status"]'::jsonb, 'Status', 'ClipboardList', true, 3),
  ('mod-review', 'Review', 'Review Hasil Asesmen', 'Peninjauan hasil asesmen sebelum keputusan akhir.', 'Ajukan Review', '["ID Pengajuan", "Nama LPK", "Reviewer", "Tanggal Review", "Status"]'::jsonb, 'Status', 'PenSquare', true, 4),
  ('mod-keputusan', 'Keputusan', 'Keputusan Akreditasi', 'Keputusan akhir status akreditasi lembaga.', 'Terbitkan Keputusan', '["ID Pengajuan", "Nama LPK", "Nomor SK", "Tanggal Keputusan", "Status"]'::jsonb, 'Status', 'Scale', true, 5),
  ('mod-sertifikat', 'Sertifikat', 'Sertifikat Akreditasi', 'Daftar sertifikat akreditasi yang telah diterbitkan.', 'Terbitkan Sertifikat', '["No. Sertifikat", "Nama LPK", "Jenis Layanan", "Tanggal Terbit", "Status"]'::jsonb, 'Status', 'Award', true, 6),
  ('mod-pembiayaan', 'Pembiayaan', 'Pembiayaan Akreditasi', 'Rincian sumber dan status pembiayaan pengajuan akreditasi.', 'Catat Pembiayaan', '["ID Pengajuan", "Nama LPK", "Sumber Dana", "Nominal", "Status"]'::jsonb, 'Status', 'Wallet', false, 7),
  ('mod-monitoring', 'Monitoring & SLA', 'Monitoring & SLA', 'Pemantauan tenggat waktu (SLA) tiap tahapan proses akreditasi.', 'Ekspor Laporan SLA', '["ID Pengajuan", "Nama LPK", "Tahap Saat Ini", "Sisa Waktu SLA", "Status"]'::jsonb, 'Status', 'Clock', false, 8),
  ('mod-laporan', 'Laporan & Analitik', 'Laporan & Analitik', 'Ringkasan performa akreditasi per wilayah dan periode.', 'Ekspor Laporan', '["Provinsi", "Jumlah Pengajuan", "Terakreditasi", "Rata-rata SLA", "Status"]'::jsonb, 'Status', 'BarChart3', false, 9)
on conflict (key) do update set
  nav_label = excluded.nav_label, cols = excluded.cols;

-- ============================================================
-- module_rows
-- ============================================================
insert into module_rows (module_key, data) values
  ('mod-pengajuan', '{"ID Pengajuan": "AKR-2026-01200", "Nama LPK": "LPK Mitra Sejahtera", "Jenis Layanan": "Akreditasi Baru", "Provinsi": "Jawa Barat", "Tanggal Ajuan": "01 Mei 2026", "Status": "Menunggu Verifikasi"}'::jsonb),
  ('mod-pengajuan', '{"ID Pengajuan": "AKR-2026-01201", "Nama LPK": "LPK Bina Mandiri", "Jenis Layanan": "Reakreditasi", "Provinsi": "Jawa Timur", "Tanggal Ajuan": "02 Mei 2026", "Status": "Dalam Proses"}'::jsonb),
  ('mod-pengajuan', '{"ID Pengajuan": "AKR-2026-01202", "Nama LPK": "LPK Cendekia Karya", "Jenis Layanan": "Penambahan Program", "Provinsi": "Jawa Tengah", "Tanggal Ajuan": "03 Mei 2026", "Status": "Terverifikasi"}'::jsonb),
  ('mod-pengajuan', '{"ID Pengajuan": "AKR-2026-01203", "Nama LPK": "LPK Nusantara Terampil", "Jenis Layanan": "Akreditasi Baru", "Provinsi": "Sumatera Utara", "Tanggal Ajuan": "04 Mei 2026", "Status": "Ditolak"}'::jsonb),
  ('mod-pengajuan', '{"ID Pengajuan": "AKR-2026-01204", "Nama LPK": "LPK Sinar Vokasi", "Jenis Layanan": "Reakreditasi", "Provinsi": "Sulawesi Selatan", "Tanggal Ajuan": "05 Mei 2026", "Status": "Menunggu Verifikasi"}'::jsonb),
  ('mod-pengajuan', '{"ID Pengajuan": "AKR-2026-01205", "Nama LPK": "LPK Karya Bangsa", "Jenis Layanan": "Penambahan Program", "Provinsi": "DKI Jakarta", "Tanggal Ajuan": "06 Mei 2026", "Status": "Dalam Proses"}'::jsonb),
  ('mod-pengajuan', '{"ID Pengajuan": "AKR-2026-01206", "Nama LPK": "LPK Terampil Jaya", "Jenis Layanan": "Akreditasi Baru", "Provinsi": "Banten", "Tanggal Ajuan": "07 Mei 2026", "Status": "Terverifikasi"}'::jsonb),
  ('mod-pengajuan', '{"ID Pengajuan": "AKR-2026-01207", "Nama LPK": "LPK Anugerah Kompeten", "Jenis Layanan": "Reakreditasi", "Provinsi": "Kalimantan Timur", "Tanggal Ajuan": "08 Mei 2026", "Status": "Ditolak"}'::jsonb),
  ('mod-pengajuan', '{"ID Pengajuan": "AKR-2026-01208", "Nama LPK": "LPK Cipta Mandiri", "Jenis Layanan": "Penambahan Program", "Provinsi": "Jawa Barat", "Tanggal Ajuan": "09 Mei 2026", "Status": "Menunggu Verifikasi"}'::jsonb),
  ('mod-pengajuan', '{"ID Pengajuan": "AKR-2026-01209", "Nama LPK": "LPK Bumi Persada", "Jenis Layanan": "Akreditasi Baru", "Provinsi": "Jawa Timur", "Tanggal Ajuan": "01 Mei 2026", "Status": "Dalam Proses"}'::jsonb),
  ('mod-pengajuan', '{"ID Pengajuan": "AKR-2026-01210", "Nama LPK": "LPK Garuda Vokasi", "Jenis Layanan": "Reakreditasi", "Provinsi": "Jawa Tengah", "Tanggal Ajuan": "02 Mei 2026", "Status": "Terverifikasi"}'::jsonb),
  ('mod-pengajuan', '{"ID Pengajuan": "AKR-2026-01211", "Nama LPK": "LPK Harapan Bangsa", "Jenis Layanan": "Penambahan Program", "Provinsi": "Sumatera Utara", "Tanggal Ajuan": "03 Mei 2026", "Status": "Ditolak"}'::jsonb),
  ('mod-verifikasi', '{"ID Pengajuan": "AKR-2026-01150", "Nama LPK": "LPK Cendekia Karya", "Petugas Verifikasi": "Dr. Ahmad Fauzi", "Tanggal": "01 Mei 2026", "Status": "Terverifikasi"}'::jsonb),
  ('mod-verifikasi', '{"ID Pengajuan": "AKR-2026-01151", "Nama LPK": "LPK Nusantara Terampil", "Petugas Verifikasi": "Siti Rahayu, M.Pd", "Tanggal": "02 Mei 2026", "Status": "Menunggu Verifikasi"}'::jsonb),
  ('mod-verifikasi', '{"ID Pengajuan": "AKR-2026-01152", "Nama LPK": "LPK Sinar Vokasi", "Petugas Verifikasi": "Budi Santoso", "Tanggal": "03 Mei 2026", "Status": "Ditolak"}'::jsonb),
  ('mod-verifikasi', '{"ID Pengajuan": "AKR-2026-01153", "Nama LPK": "LPK Karya Bangsa", "Petugas Verifikasi": "Rina Kartika, S.T", "Tanggal": "04 Mei 2026", "Status": "Terverifikasi"}'::jsonb),
  ('mod-verifikasi', '{"ID Pengajuan": "AKR-2026-01154", "Nama LPK": "LPK Terampil Jaya", "Petugas Verifikasi": "Hendra Wijaya", "Tanggal": "05 Mei 2026", "Status": "Menunggu Verifikasi"}'::jsonb),
  ('mod-verifikasi', '{"ID Pengajuan": "AKR-2026-01155", "Nama LPK": "LPK Anugerah Kompeten", "Petugas Verifikasi": "Dewi Lestari", "Tanggal": "06 Mei 2026", "Status": "Ditolak"}'::jsonb),
  ('mod-verifikasi', '{"ID Pengajuan": "AKR-2026-01156", "Nama LPK": "LPK Cipta Mandiri", "Petugas Verifikasi": "Agus Setiawan", "Tanggal": "07 Mei 2026", "Status": "Terverifikasi"}'::jsonb),
  ('mod-verifikasi', '{"ID Pengajuan": "AKR-2026-01157", "Nama LPK": "LPK Bumi Persada", "Petugas Verifikasi": "Maya Puspita", "Tanggal": "08 Mei 2026", "Status": "Menunggu Verifikasi"}'::jsonb),
  ('mod-verifikasi', '{"ID Pengajuan": "AKR-2026-01158", "Nama LPK": "LPK Garuda Vokasi", "Petugas Verifikasi": "Rudi Hartono", "Tanggal": "09 Mei 2026", "Status": "Ditolak"}'::jsonb),
  ('mod-verifikasi', '{"ID Pengajuan": "AKR-2026-01159", "Nama LPK": "LPK Harapan Bangsa", "Petugas Verifikasi": "Fitri Anggraini", "Tanggal": "01 Mei 2026", "Status": "Terverifikasi"}'::jsonb),
  ('mod-verifikasi', '{"ID Pengajuan": "AKR-2026-01160", "Nama LPK": "LPK Mitra Sejahtera", "Petugas Verifikasi": "Dr. Ahmad Fauzi", "Tanggal": "02 Mei 2026", "Status": "Menunggu Verifikasi"}'::jsonb),
  ('mod-verifikasi', '{"ID Pengajuan": "AKR-2026-01161", "Nama LPK": "LPK Bina Mandiri", "Petugas Verifikasi": "Siti Rahayu, M.Pd", "Tanggal": "03 Mei 2026", "Status": "Ditolak"}'::jsonb),
  ('mod-penugasan', '{"ID Pengajuan": "AKR-2026-01100", "Nama LPK": "LPK Sinar Vokasi", "Asesor Ditugaskan": "Siti Rahayu, M.Pd", "Tanggal Penugasan": "01 Mei 2026", "Status": "Terjadwal"}'::jsonb),
  ('mod-penugasan', '{"ID Pengajuan": "AKR-2026-01101", "Nama LPK": "LPK Karya Bangsa", "Asesor Ditugaskan": "Budi Santoso", "Tanggal Penugasan": "02 Mei 2026", "Status": "Dalam Proses"}'::jsonb),
  ('mod-penugasan', '{"ID Pengajuan": "AKR-2026-01102", "Nama LPK": "LPK Terampil Jaya", "Asesor Ditugaskan": "Rina Kartika, S.T", "Tanggal Penugasan": "03 Mei 2026", "Status": "Selesai"}'::jsonb),
  ('mod-penugasan', '{"ID Pengajuan": "AKR-2026-01103", "Nama LPK": "LPK Anugerah Kompeten", "Asesor Ditugaskan": "Hendra Wijaya", "Tanggal Penugasan": "04 Mei 2026", "Status": "Terjadwal"}'::jsonb),
  ('mod-penugasan', '{"ID Pengajuan": "AKR-2026-01104", "Nama LPK": "LPK Cipta Mandiri", "Asesor Ditugaskan": "Dewi Lestari", "Tanggal Penugasan": "05 Mei 2026", "Status": "Dalam Proses"}'::jsonb),
  ('mod-penugasan', '{"ID Pengajuan": "AKR-2026-01105", "Nama LPK": "LPK Bumi Persada", "Asesor Ditugaskan": "Agus Setiawan", "Tanggal Penugasan": "06 Mei 2026", "Status": "Selesai"}'::jsonb),
  ('mod-penugasan', '{"ID Pengajuan": "AKR-2026-01106", "Nama LPK": "LPK Garuda Vokasi", "Asesor Ditugaskan": "Maya Puspita", "Tanggal Penugasan": "07 Mei 2026", "Status": "Terjadwal"}'::jsonb),
  ('mod-penugasan', '{"ID Pengajuan": "AKR-2026-01107", "Nama LPK": "LPK Harapan Bangsa", "Asesor Ditugaskan": "Rudi Hartono", "Tanggal Penugasan": "08 Mei 2026", "Status": "Dalam Proses"}'::jsonb),
  ('mod-penugasan', '{"ID Pengajuan": "AKR-2026-01108", "Nama LPK": "LPK Mitra Sejahtera", "Asesor Ditugaskan": "Fitri Anggraini", "Tanggal Penugasan": "09 Mei 2026", "Status": "Selesai"}'::jsonb),
  ('mod-penugasan', '{"ID Pengajuan": "AKR-2026-01109", "Nama LPK": "LPK Bina Mandiri", "Asesor Ditugaskan": "Dr. Ahmad Fauzi", "Tanggal Penugasan": "01 Mei 2026", "Status": "Terjadwal"}'::jsonb),
  ('mod-penugasan', '{"ID Pengajuan": "AKR-2026-01110", "Nama LPK": "LPK Cendekia Karya", "Asesor Ditugaskan": "Siti Rahayu, M.Pd", "Tanggal Penugasan": "02 Mei 2026", "Status": "Dalam Proses"}'::jsonb),
  ('mod-penugasan', '{"ID Pengajuan": "AKR-2026-01111", "Nama LPK": "LPK Nusantara Terampil", "Asesor Ditugaskan": "Budi Santoso", "Tanggal Penugasan": "03 Mei 2026", "Status": "Selesai"}'::jsonb),
  ('mod-asesmen', '{"ID Pengajuan": "AKR-2026-01080", "Nama LPK": "LPK Terampil Jaya", "Asesor": "Rina Kartika, S.T", "Tanggal Asesmen": "01 Mei 2026", "Status": "Terjadwal"}'::jsonb),
  ('mod-asesmen', '{"ID Pengajuan": "AKR-2026-01081", "Nama LPK": "LPK Anugerah Kompeten", "Asesor": "Hendra Wijaya", "Tanggal Asesmen": "02 Mei 2026", "Status": "Dalam Proses"}'::jsonb),
  ('mod-asesmen', '{"ID Pengajuan": "AKR-2026-01082", "Nama LPK": "LPK Cipta Mandiri", "Asesor": "Dewi Lestari", "Tanggal Asesmen": "03 Mei 2026", "Status": "Selesai"}'::jsonb),
  ('mod-asesmen', '{"ID Pengajuan": "AKR-2026-01083", "Nama LPK": "LPK Bumi Persada", "Asesor": "Agus Setiawan", "Tanggal Asesmen": "04 Mei 2026", "Status": "Terjadwal"}'::jsonb),
  ('mod-asesmen', '{"ID Pengajuan": "AKR-2026-01084", "Nama LPK": "LPK Garuda Vokasi", "Asesor": "Maya Puspita", "Tanggal Asesmen": "05 Mei 2026", "Status": "Dalam Proses"}'::jsonb),
  ('mod-asesmen', '{"ID Pengajuan": "AKR-2026-01085", "Nama LPK": "LPK Harapan Bangsa", "Asesor": "Rudi Hartono", "Tanggal Asesmen": "06 Mei 2026", "Status": "Selesai"}'::jsonb),
  ('mod-asesmen', '{"ID Pengajuan": "AKR-2026-01086", "Nama LPK": "LPK Mitra Sejahtera", "Asesor": "Fitri Anggraini", "Tanggal Asesmen": "07 Mei 2026", "Status": "Terjadwal"}'::jsonb),
  ('mod-asesmen', '{"ID Pengajuan": "AKR-2026-01087", "Nama LPK": "LPK Bina Mandiri", "Asesor": "Dr. Ahmad Fauzi", "Tanggal Asesmen": "08 Mei 2026", "Status": "Dalam Proses"}'::jsonb),
  ('mod-asesmen', '{"ID Pengajuan": "AKR-2026-01088", "Nama LPK": "LPK Cendekia Karya", "Asesor": "Siti Rahayu, M.Pd", "Tanggal Asesmen": "09 Mei 2026", "Status": "Selesai"}'::jsonb),
  ('mod-asesmen', '{"ID Pengajuan": "AKR-2026-01089", "Nama LPK": "LPK Nusantara Terampil", "Asesor": "Budi Santoso", "Tanggal Asesmen": "01 Mei 2026", "Status": "Terjadwal"}'::jsonb),
  ('mod-asesmen', '{"ID Pengajuan": "AKR-2026-01090", "Nama LPK": "LPK Sinar Vokasi", "Asesor": "Rina Kartika, S.T", "Tanggal Asesmen": "02 Mei 2026", "Status": "Dalam Proses"}'::jsonb),
  ('mod-asesmen', '{"ID Pengajuan": "AKR-2026-01091", "Nama LPK": "LPK Karya Bangsa", "Asesor": "Hendra Wijaya", "Tanggal Asesmen": "03 Mei 2026", "Status": "Selesai"}'::jsonb),
  ('mod-review', '{"ID Pengajuan": "AKR-2026-01050", "Nama LPK": "LPK Bina Mandiri", "Reviewer": "Dewi Lestari", "Tanggal Review": "01 Mei 2026", "Status": "Ditinjau"}'::jsonb),
  ('mod-review', '{"ID Pengajuan": "AKR-2026-01051", "Nama LPK": "LPK Cendekia Karya", "Reviewer": "Agus Setiawan", "Tanggal Review": "02 Mei 2026", "Status": "Disetujui"}'::jsonb),
  ('mod-review', '{"ID Pengajuan": "AKR-2026-01052", "Nama LPK": "LPK Nusantara Terampil", "Reviewer": "Maya Puspita", "Tanggal Review": "03 Mei 2026", "Status": "Ditolak"}'::jsonb),
  ('mod-review', '{"ID Pengajuan": "AKR-2026-01053", "Nama LPK": "LPK Sinar Vokasi", "Reviewer": "Rudi Hartono", "Tanggal Review": "04 Mei 2026", "Status": "Ditinjau"}'::jsonb),
  ('mod-review', '{"ID Pengajuan": "AKR-2026-01054", "Nama LPK": "LPK Karya Bangsa", "Reviewer": "Fitri Anggraini", "Tanggal Review": "05 Mei 2026", "Status": "Disetujui"}'::jsonb),
  ('mod-review', '{"ID Pengajuan": "AKR-2026-01055", "Nama LPK": "LPK Terampil Jaya", "Reviewer": "Dr. Ahmad Fauzi", "Tanggal Review": "06 Mei 2026", "Status": "Ditolak"}'::jsonb),
  ('mod-review', '{"ID Pengajuan": "AKR-2026-01056", "Nama LPK": "LPK Anugerah Kompeten", "Reviewer": "Siti Rahayu, M.Pd", "Tanggal Review": "07 Mei 2026", "Status": "Ditinjau"}'::jsonb),
  ('mod-review', '{"ID Pengajuan": "AKR-2026-01057", "Nama LPK": "LPK Cipta Mandiri", "Reviewer": "Budi Santoso", "Tanggal Review": "08 Mei 2026", "Status": "Disetujui"}'::jsonb),
  ('mod-review', '{"ID Pengajuan": "AKR-2026-01058", "Nama LPK": "LPK Bumi Persada", "Reviewer": "Rina Kartika, S.T", "Tanggal Review": "09 Mei 2026", "Status": "Ditolak"}'::jsonb),
  ('mod-review', '{"ID Pengajuan": "AKR-2026-01059", "Nama LPK": "LPK Garuda Vokasi", "Reviewer": "Hendra Wijaya", "Tanggal Review": "01 Mei 2026", "Status": "Ditinjau"}'::jsonb),
  ('mod-keputusan', '{"ID Pengajuan": "AKR-2026-01020", "Nama LPK": "LPK Anugerah Kompeten", "Nomor SK": "SK/400/LTV/2026", "Tanggal Keputusan": "01 Mei 2026", "Status": "Disetujui"}'::jsonb),
  ('mod-keputusan', '{"ID Pengajuan": "AKR-2026-01021", "Nama LPK": "LPK Cipta Mandiri", "Nomor SK": "SK/401/LTV/2026", "Tanggal Keputusan": "02 Mei 2026", "Status": "Ditinjau"}'::jsonb),
  ('mod-keputusan', '{"ID Pengajuan": "AKR-2026-01022", "Nama LPK": "LPK Bumi Persada", "Nomor SK": "SK/402/LTV/2026", "Tanggal Keputusan": "03 Mei 2026", "Status": "Ditolak"}'::jsonb),
  ('mod-keputusan', '{"ID Pengajuan": "AKR-2026-01023", "Nama LPK": "LPK Garuda Vokasi", "Nomor SK": "SK/403/LTV/2026", "Tanggal Keputusan": "04 Mei 2026", "Status": "Disetujui"}'::jsonb),
  ('mod-keputusan', '{"ID Pengajuan": "AKR-2026-01024", "Nama LPK": "LPK Harapan Bangsa", "Nomor SK": "SK/404/LTV/2026", "Tanggal Keputusan": "05 Mei 2026", "Status": "Ditinjau"}'::jsonb),
  ('mod-keputusan', '{"ID Pengajuan": "AKR-2026-01025", "Nama LPK": "LPK Mitra Sejahtera", "Nomor SK": "SK/405/LTV/2026", "Tanggal Keputusan": "06 Mei 2026", "Status": "Ditolak"}'::jsonb),
  ('mod-keputusan', '{"ID Pengajuan": "AKR-2026-01026", "Nama LPK": "LPK Bina Mandiri", "Nomor SK": "SK/406/LTV/2026", "Tanggal Keputusan": "07 Mei 2026", "Status": "Disetujui"}'::jsonb),
  ('mod-keputusan', '{"ID Pengajuan": "AKR-2026-01027", "Nama LPK": "LPK Cendekia Karya", "Nomor SK": "SK/407/LTV/2026", "Tanggal Keputusan": "08 Mei 2026", "Status": "Ditinjau"}'::jsonb),
  ('mod-keputusan', '{"ID Pengajuan": "AKR-2026-01028", "Nama LPK": "LPK Nusantara Terampil", "Nomor SK": "SK/408/LTV/2026", "Tanggal Keputusan": "09 Mei 2026", "Status": "Ditolak"}'::jsonb),
  ('mod-keputusan', '{"ID Pengajuan": "AKR-2026-01029", "Nama LPK": "LPK Sinar Vokasi", "Nomor SK": "SK/409/LTV/2026", "Tanggal Keputusan": "01 Mei 2026", "Status": "Disetujui"}'::jsonb),
  ('mod-sertifikat', '{"No. Sertifikat": "SERT-2026-0700", "Nama LPK": "LPK Mitra Sejahtera", "Jenis Layanan": "Akreditasi Baru", "Tanggal Terbit": "01 Mei 2026", "Status": "Terbit"}'::jsonb),
  ('mod-sertifikat', '{"No. Sertifikat": "SERT-2026-0701", "Nama LPK": "LPK Bina Mandiri", "Jenis Layanan": "Reakreditasi", "Tanggal Terbit": "02 Mei 2026", "Status": "Diproses"}'::jsonb),
  ('mod-sertifikat', '{"No. Sertifikat": "SERT-2026-0702", "Nama LPK": "LPK Cendekia Karya", "Jenis Layanan": "Akreditasi Baru", "Tanggal Terbit": "03 Mei 2026", "Status": "Terbit"}'::jsonb),
  ('mod-sertifikat', '{"No. Sertifikat": "SERT-2026-0703", "Nama LPK": "LPK Nusantara Terampil", "Jenis Layanan": "Reakreditasi", "Tanggal Terbit": "04 Mei 2026", "Status": "Diproses"}'::jsonb),
  ('mod-sertifikat', '{"No. Sertifikat": "SERT-2026-0704", "Nama LPK": "LPK Sinar Vokasi", "Jenis Layanan": "Akreditasi Baru", "Tanggal Terbit": "05 Mei 2026", "Status": "Terbit"}'::jsonb),
  ('mod-sertifikat', '{"No. Sertifikat": "SERT-2026-0705", "Nama LPK": "LPK Karya Bangsa", "Jenis Layanan": "Reakreditasi", "Tanggal Terbit": "06 Mei 2026", "Status": "Diproses"}'::jsonb),
  ('mod-sertifikat', '{"No. Sertifikat": "SERT-2026-0706", "Nama LPK": "LPK Terampil Jaya", "Jenis Layanan": "Akreditasi Baru", "Tanggal Terbit": "07 Mei 2026", "Status": "Terbit"}'::jsonb),
  ('mod-sertifikat', '{"No. Sertifikat": "SERT-2026-0707", "Nama LPK": "LPK Anugerah Kompeten", "Jenis Layanan": "Reakreditasi", "Tanggal Terbit": "08 Mei 2026", "Status": "Diproses"}'::jsonb),
  ('mod-sertifikat', '{"No. Sertifikat": "SERT-2026-0708", "Nama LPK": "LPK Cipta Mandiri", "Jenis Layanan": "Akreditasi Baru", "Tanggal Terbit": "09 Mei 2026", "Status": "Terbit"}'::jsonb),
  ('mod-sertifikat', '{"No. Sertifikat": "SERT-2026-0709", "Nama LPK": "LPK Bumi Persada", "Jenis Layanan": "Reakreditasi", "Tanggal Terbit": "01 Mei 2026", "Status": "Diproses"}'::jsonb),
  ('mod-sertifikat', '{"No. Sertifikat": "SERT-2026-0710", "Nama LPK": "LPK Garuda Vokasi", "Jenis Layanan": "Akreditasi Baru", "Tanggal Terbit": "02 Mei 2026", "Status": "Terbit"}'::jsonb),
  ('mod-sertifikat', '{"No. Sertifikat": "SERT-2026-0711", "Nama LPK": "LPK Harapan Bangsa", "Jenis Layanan": "Reakreditasi", "Tanggal Terbit": "03 Mei 2026", "Status": "Diproses"}'::jsonb),
  ('mod-pembiayaan', '{"ID Pengajuan": "AKR-2026-01300", "Nama LPK": "LPK Nusantara Terampil", "Sumber Dana": "APBN", "Nominal": "Rp 15.500.000", "Status": "Cair"}'::jsonb),
  ('mod-pembiayaan', '{"ID Pengajuan": "AKR-2026-01301", "Nama LPK": "LPK Sinar Vokasi", "Sumber Dana": "APBD", "Nominal": "Rp 16.500.000", "Status": "Pending"}'::jsonb),
  ('mod-pembiayaan', '{"ID Pengajuan": "AKR-2026-01302", "Nama LPK": "LPK Karya Bangsa", "Sumber Dana": "Mandiri", "Nominal": "Rp 17.500.000", "Status": "Diproses"}'::jsonb),
  ('mod-pembiayaan', '{"ID Pengajuan": "AKR-2026-01303", "Nama LPK": "LPK Terampil Jaya", "Sumber Dana": "APBN", "Nominal": "Rp 18.500.000", "Status": "Cair"}'::jsonb),
  ('mod-pembiayaan', '{"ID Pengajuan": "AKR-2026-01304", "Nama LPK": "LPK Anugerah Kompeten", "Sumber Dana": "APBD", "Nominal": "Rp 19.500.000", "Status": "Pending"}'::jsonb),
  ('mod-pembiayaan', '{"ID Pengajuan": "AKR-2026-01305", "Nama LPK": "LPK Cipta Mandiri", "Sumber Dana": "Mandiri", "Nominal": "Rp 20.500.000", "Status": "Diproses"}'::jsonb),
  ('mod-pembiayaan', '{"ID Pengajuan": "AKR-2026-01306", "Nama LPK": "LPK Bumi Persada", "Sumber Dana": "APBN", "Nominal": "Rp 21.500.000", "Status": "Cair"}'::jsonb),
  ('mod-pembiayaan', '{"ID Pengajuan": "AKR-2026-01307", "Nama LPK": "LPK Garuda Vokasi", "Sumber Dana": "APBD", "Nominal": "Rp 22.500.000", "Status": "Pending"}'::jsonb),
  ('mod-pembiayaan', '{"ID Pengajuan": "AKR-2026-01308", "Nama LPK": "LPK Harapan Bangsa", "Sumber Dana": "Mandiri", "Nominal": "Rp 23.500.000", "Status": "Diproses"}'::jsonb),
  ('mod-pembiayaan', '{"ID Pengajuan": "AKR-2026-01309", "Nama LPK": "LPK Mitra Sejahtera", "Sumber Dana": "APBN", "Nominal": "Rp 24.500.000", "Status": "Cair"}'::jsonb),
  ('mod-pembiayaan', '{"ID Pengajuan": "AKR-2026-01310", "Nama LPK": "LPK Bina Mandiri", "Sumber Dana": "APBD", "Nominal": "Rp 25.500.000", "Status": "Pending"}'::jsonb),
  ('mod-pembiayaan', '{"ID Pengajuan": "AKR-2026-01311", "Nama LPK": "LPK Cendekia Karya", "Sumber Dana": "Mandiri", "Nominal": "Rp 26.500.000", "Status": "Diproses"}'::jsonb),
  ('mod-monitoring', '{"ID Pengajuan": "AKR-2026-01400", "Nama LPK": "LPK Cipta Mandiri", "Tahap Saat Ini": "Verifikasi", "Sisa Waktu SLA": "Terlampaui", "Status": "Kritis"}'::jsonb),
  ('mod-monitoring', '{"ID Pengajuan": "AKR-2026-01401", "Nama LPK": "LPK Bumi Persada", "Tahap Saat Ini": "Asesmen", "Sisa Waktu SLA": "4 hari", "Status": "Normal"}'::jsonb),
  ('mod-monitoring', '{"ID Pengajuan": "AKR-2026-01402", "Nama LPK": "LPK Garuda Vokasi", "Tahap Saat Ini": "Review", "Sisa Waktu SLA": "5 hari", "Status": "Normal"}'::jsonb),
  ('mod-monitoring', '{"ID Pengajuan": "AKR-2026-01403", "Nama LPK": "LPK Harapan Bangsa", "Tahap Saat Ini": "Keputusan", "Sisa Waktu SLA": "6 hari", "Status": "Perhatian"}'::jsonb),
  ('mod-monitoring', '{"ID Pengajuan": "AKR-2026-01404", "Nama LPK": "LPK Mitra Sejahtera", "Tahap Saat Ini": "Verifikasi", "Sisa Waktu SLA": "7 hari", "Status": "Normal"}'::jsonb),
  ('mod-monitoring', '{"ID Pengajuan": "AKR-2026-01405", "Nama LPK": "LPK Bina Mandiri", "Tahap Saat Ini": "Asesmen", "Sisa Waktu SLA": "Terlampaui", "Status": "Kritis"}'::jsonb),
  ('mod-monitoring', '{"ID Pengajuan": "AKR-2026-01406", "Nama LPK": "LPK Cendekia Karya", "Tahap Saat Ini": "Review", "Sisa Waktu SLA": "9 hari", "Status": "Perhatian"}'::jsonb),
  ('mod-monitoring', '{"ID Pengajuan": "AKR-2026-01407", "Nama LPK": "LPK Nusantara Terampil", "Tahap Saat Ini": "Keputusan", "Sisa Waktu SLA": "10 hari", "Status": "Normal"}'::jsonb),
  ('mod-monitoring', '{"ID Pengajuan": "AKR-2026-01408", "Nama LPK": "LPK Sinar Vokasi", "Tahap Saat Ini": "Verifikasi", "Sisa Waktu SLA": "11 hari", "Status": "Normal"}'::jsonb),
  ('mod-monitoring', '{"ID Pengajuan": "AKR-2026-01409", "Nama LPK": "LPK Karya Bangsa", "Tahap Saat Ini": "Asesmen", "Sisa Waktu SLA": "12 hari", "Status": "Perhatian"}'::jsonb),
  ('mod-monitoring', '{"ID Pengajuan": "AKR-2026-01410", "Nama LPK": "LPK Terampil Jaya", "Tahap Saat Ini": "Review", "Sisa Waktu SLA": "Terlampaui", "Status": "Kritis"}'::jsonb),
  ('mod-monitoring', '{"ID Pengajuan": "AKR-2026-01411", "Nama LPK": "LPK Anugerah Kompeten", "Tahap Saat Ini": "Keputusan", "Sisa Waktu SLA": "4 hari", "Status": "Normal"}'::jsonb),
  ('mod-laporan', '{"Provinsi": "Jawa Barat", "Jumlah Pengajuan": 214, "Terakreditasi": 160, "Rata-rata SLA": "5 hari", "Status": "Normal"}'::jsonb),
  ('mod-laporan', '{"Provinsi": "Jawa Timur", "Jumlah Pengajuan": 192, "Terakreditasi": 145, "Rata-rata SLA": "6 hari", "Status": "Perhatian"}'::jsonb),
  ('mod-laporan', '{"Provinsi": "Jawa Tengah", "Jumlah Pengajuan": 170, "Terakreditasi": 130, "Rata-rata SLA": "7 hari", "Status": "Normal"}'::jsonb),
  ('mod-laporan', '{"Provinsi": "Sumatera Utara", "Jumlah Pengajuan": 148, "Terakreditasi": 115, "Rata-rata SLA": "8 hari", "Status": "Normal"}'::jsonb),
  ('mod-laporan', '{"Provinsi": "Sulawesi Selatan", "Jumlah Pengajuan": 126, "Terakreditasi": 100, "Rata-rata SLA": "9 hari", "Status": "Perhatian"}'::jsonb),
  ('mod-laporan', '{"Provinsi": "DKI Jakarta", "Jumlah Pengajuan": 104, "Terakreditasi": 85, "Rata-rata SLA": "10 hari", "Status": "Normal"}'::jsonb),
  ('mod-laporan', '{"Provinsi": "Banten", "Jumlah Pengajuan": 82, "Terakreditasi": 70, "Rata-rata SLA": "11 hari", "Status": "Normal"}'::jsonb),
  ('mod-laporan', '{"Provinsi": "Kalimantan Timur", "Jumlah Pengajuan": 60, "Terakreditasi": 55, "Rata-rata SLA": "12 hari", "Status": "Perhatian"}'::jsonb);
